import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/global.scss";
import "../../styles/default.scss";
import "../../styles/values.scss";
import React from "react";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
    params
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string
  }
}>)
{
  const messages = await getMessages();

  return (
    <html lang={params.locale}>
    <head>
      <title>The top</title>

      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Libre+Barcode+128+Text&display=swap" rel="stylesheet"/>
    </head>
    <body className={inter.className}>
      <NextIntlClientProvider messages={messages}>
        {children}
      </NextIntlClientProvider>
    </body>
    </html>
  );
}
